version: "3.9"
services:
  web:
    build: ./app
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports: ['5000:5000']
    volumes: ['./app:/app']

  db:
    image: mysql
    ports:
      - "32000:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: seznam123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# volumes:
#   myapp:
#     external: true
  